# Generated by Django 4.2.3 on 2023-08-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_services.normaluser')),
                ('followings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='user_services.normaluser')),
            ],
            options={
                'unique_together': {('followers', 'followings')},
            },
        ),
    ]
