# Generated by Django 4.2.3 on 2023-08-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_services', '0006_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('definition', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user_services.normaluser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_services.post')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
