# Generated by Django 4.2.3 on 2023-08-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_check', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfirmation',
        ),
    ]
